export const LOGIN_URL = process.env.REACT_APP_ENDPOINT+'admin/login'
export const USER_GET_LENGTH = process.env.REACT_APP_ENDPOINT+'user/getlength'
export const VIDEOES_GET_LENGTH = process.env.REACT_APP_ENDPOINT+'videos/getlength'
export const HOUSES_GET_LENGTH = process.env.REACT_APP_ENDPOINT+'house/getlength'
export const GET_ALL_ADMINS = process.env.REACT_APP_ENDPOINT+'admin/get'
export const GET_ALL_USERS = process.env.REACT_APP_ENDPOINT+ 'user/getuser'
export const GET_ALL_VIDEOS = process.env.REACT_APP_ENDPOINT+ 'videos/get'
export const GET_ALL_HOUSES = process.env.REACT_APP_ENDPOINT+ 'house/get'